### ISSUE TITLE
Lessons out of order

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/fe-zetsy#1]
I just completed the Zetsy and ZHW Shoe assignments. I am now about to take the new lesson, the introduction to CSS. These lessons seem to be out of order. Looking at what is covered, I can see that all the CSS that I have been googling around to get through those assignments is about to be covered.

**Comment by AnnJohn** [comment]
@SophieDeBenedetto @jmburges Is this an issue because of the pre-work reorganization?

**Comment by AnnJohn** [comment]
@aturkewi could you post a screenshot of your navigation/menu bar on Learn. Zetsy and ZHW should come several lessons after the Introduction to CSS lesson.

**Comment by AnnJohn** [comment]
Issue fixed. Closing.
