### ISSUE TITLE
editor for autocomplete coding from scratch assignment, Zetsy

### ISSUE THREAD

**Issue by ICanDoAllThingThroughChrist** [learn-co-curriculum/fe-zetsy#12]
though one could easily copy and paste the codes from Chrome, i am finding that I don't learn anything this way.  what is the job guarantee editor on the resume, which Flatiron recommends?

**Comment by gj** [comment]
Hi @ICanDoAllThingThroughChrist !

Could you elaborate a bit on this? I'm having trouble understanding the problem. Thanks!

**Comment by ICanDoAllThingThroughChrist** [comment]
The problem was, 10 months ago,  lack of recommendation from flatiron, for code editor like sublime outside of learn I D E.

**Comment by gj** [comment]
Gotcha! We recommend the Learn IDE, and, after that, Atom and Sublime are about equal. Going to close this one now. Thanks!
