### ISSUE TITLE
instructions indicate tools for Mac users only

### ISSUE THREAD

**Issue by Matthew-Daly** [learn-co-curriculum/fe-zetsy#14]
In this lesson as well, as well as many in the HTML/CSS section, the instructor keeps on using terminology and tools that specific to the Mac. In this case, the Digital Color Metter App. Not all students are using Macs and it might be nice to have alternatives for Windows and Linux users.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @Matthew-Daly.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
