### ISSUE TITLE
Tests missing

### ISSUE THREAD

**Issue by FreeBreadsticks** [learn-co-curriculum/fe-zetsy#19]
It looks like the tests are missing on this lab, but the spec folder is present in the solution

**Comment by kwebster2** [comment]
@maxwellbenton 
I believe this lesson should just require a PR, rather than a PR and passing tests

**Comment by d-d-d-dalia** [comment]
Still an issue. When trying to run learn from solution branch, `Please install Selenium Standalone` come back.

**Comment by lizbur10** [comment]
Closing as outdated
