### ISSUE TITLE
Lab requires missing local tests to pass

### ISSUE THREAD

**Issue by trevor-jameson** [learn-co-curriculum/fe-zetsy#21]
The Zetsy lab requires local tests to pass to mark as completed, however .spec files are not included in the master branch.

![zetsy-lesson-requirements](https://user-images.githubusercontent.com/19979089/44595579-78991a00-a797-11e8-8269-b0ed5364e5c1.png)

**Comment by marycodes2** [comment]
I have the same problem. Please help. Thanks!

**Comment by d-d-d-dalia** [comment]
Had a student with this issue today.

**Comment by taoliu12** [comment]
Still unfixed

**Comment by lizbur10** [comment]
Closing as outdated
