### ISSUE TITLE
All Module 11 Section 2 labs - tests never fail

### ISSUE THREAD

**Issue by boom100100** [learn-co-curriculum/fe-zetsy#25]
Course page doesn't indicate any changes required to make learn command fail tests. Spec only has a single test that doesn't check content of CSS files. Pointing index.html file in Zetsy to ./css/style.css doesn't cause tests to fail. So it's not possible for a user to determine if their code makes any difference in achieving the goal via the Learn IDE alone.

https://learn.co/tracks/full-stack-web-development-v8/module-11-css-continued/section-2-page-layout-and-box-styles/creating-columns-lab
https://learn.co/tracks/full-stack-web-development-v8/module-11-css-continued/section-2-page-layout-and-box-styles/zetsy
https://learn.co/tracks/full-stack-web-development-v8/module-11-css-continued/section-2-page-layout-and-box-styles/box-style-lab

**Comment by lizbur10** [comment]
Closing as outdated
