### ISSUE TITLE
Discrepancy in live and MOCKUP.jpg

### ISSUE THREAD

**Issue by yoshikot** [learn-co-curriculum/fe-zetsy#3]
The h1 in the live page example does not look as it does in MOCKUP.jpg.

![image](https://cloud.githubusercontent.com/assets/7904011/11665150/d1111084-9db3-11e5-9062-2b73e1863ba4.png)

**Comment by AnnJohn** [comment]
Thanks for raising this issue @yoshikot! Will get to it as soon as we can.

**Comment by jongrover** [comment]
This is a known issue in Chrome: https://code.google.com/p/chromium/issues/detail?id=31833
Until the Chrome team fixes this it will look off.
