### ISSUE TITLE
Change link to NMAI home page

### ISSUE THREAD

**Issue by m00se333** [learn-co-curriculum/fe-zetsy#4]
I tried to make this change myself in the learn-co-curriculum branch but I didn't have access rights probably for good reason.

In the file `SOURCE.md` under the press images `[nmai-logo.png]<!-- links to: http://nmai.si.edu/home/ -->` [takes you to this page](http://nmai.si.edu/home/) which is just a page that tells you to go to their new home page which is simply [http://nmai.si.edu](http://nmai.si.edu/). 
So instead of having a comment that reads:

```
<!-- links to http://nmai.si.edu/home -->
```

change it to

```
<!-- links to http://nmai.si.edu -->
```

I know it isn't the most pressing matter but for the sake of correctness I figured I would point it out.

**Comment by jongrover** [comment]
Thanks @m00se333 I fixed this in commit e96dca9.
