### ISSUE TITLE
Live Preview html

### ISSUE THREAD

**Issue by just-Bri** [learn-co-curriculum/fe-zetsy#5]
The alt on the Bergdorf img src is misspelled.

**Comment by AnnJohn** [comment]
thanks @reifnotreef for raising this issue. 

@jongrover if you get a chance, can you fix?

**Comment by just-Bri** [comment]
I just submitted the edit.
I didn't know I could do that via github, only on Learn.co!

**Comment by AnnJohn** [comment]
Great, thanks!
