### ISSUE TITLE
MOCKUP image is incorrect

### ISSUE THREAD

**Issue by kode-tiki** [learn-co-curriculum/fe-zetsy#8]
In your MOCKUP.jpg image, the "Zetsy" at the top is not in the Baskerville.ttc font, as it is supposed to be. It is in whatever the default serif font is. Open your live page in Chrome, which supports ttc fonts, and you will see an obvious difference between that and the MOCKUP.

**Comment by maxwellbenton** [comment]
Hi there,

We have changed the instructions for this lab, and believe that this issue is no longer a concern, so I'm going to close it for now.

As always, thanks for contributing! 💙
If you do not believe that this issue has been addressed, please re-open this issue. 💙
