### ISSUE TITLE
One of the image files is corrupt.

### ISSUE THREAD

**Issue by alexcrisan** [learn-co-curriculum/fe-zetsy#9]
Not sure if this is just in my project, but the bergdorf-logo.png image file is corrupt for this project. Just letting you know in case anyone else runs across this issue. 

Thanks,

Alex

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @alexcrisan.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
